#ifndef PALOMA_PARAMETERS_H
#define PALOMA_PARAMETERS_H

//  Set these three values apropriately for your algorithm
// PALOMA1
#if PALOMA_MODE == 1 
#define CRYPTO_ALGNAME "PALOMA128"
#define PALOMA_SECRETKEYBYTES       93008
#define PALOMA_PUBLICKEYBYTES       319488 
#define PALOMA_CRYPTO_BYTES         32
#define PALOMA_CIPHERTEXTBYTES      136 
// PALOMA2
#elif PALOMA_MODE == 3
#define CRYPTO_ALGNAME "PALOMA192"
#define PALOMA_SECRETKEYBYTES       355400
#define PALOMA_PUBLICKEYBYTES       812032 
#define PALOMA_CRYPTO_BYTES         32
#define PALOMA_CIPHERTEXTBYTES      240 
// PALOMA3
#elif PALOMA_MODE == 5
#define CRYPTO_ALGNAME "PALOMA256"
#define PALOMA_SECRETKEYBYTES       357064
#define PALOMA_PUBLICKEYBYTES       1025024 
#define PALOMA_CRYPTO_BYTES         32
#define PALOMA_CIPHERTEXTBYTES      240 


#endif
#endif // PALOMA_PARAMETERS_H



